<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
   <div style="background-color:#cccccc; text-align:left; vertical-align: top; padding:0px 0px; opacity: 0.8; width: 50%;">
	<dd> <?php 
		$xml = simplexml_load_file('templates/planes/planeDescription.xml') or die("Error: Cannot create object");	
	?>
		
	</dd>
	<h2>The plane for you is ....</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				$ans = $answer 
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				
				if ($ans == 'Sorry, we can not find a suitable plane for you based on your preferences.'){
					echo $ans;
				} else {
					$count = 0;
					$sans = preg_replace('/\s/', '', $ans);
					foreach($xml->children() as $planes) { 
						$name = preg_replace('/\s/', '', $planes->name->__toString()); 

						if (strcmp($sans, $name) == 0) {
							$count = 1;
							if ($planes->name != 'N/A') {echo "name     : " . $planes->name     . "<br>";}
							if ($planes->price != 'N/A') {echo "price    : " . $planes->price    . "<br>";}
							if ($planes->seats != 'N/A') {echo "seats    : " . $planes->seats    . "<br>";}
							if ($planes->purpose != 'N/A') {echo "purpose  : " . $planes->purpose  . "<br>";}
							if ($planes->niveau != 'N/A') {echo "skill level : " . $planes->niveau   . "<br>";}
							if ($planes->flaps != 'N/A') {echo "flaps    : " . $planes->flaps    . "<br>";}
							if ($planes->year != 'N/A') {echo "year     : " . $planes->year     . "<br>";}
							if ($planes->wingspan != 'N/A') {echo "wingspan : " . $planes->wingspan . "<br>";}
							if ($planes->class != 'N/A') {echo "class    : " . $planes->class    . "<br>";}  
						}
						if (count == 0){
							echo $ans;
						}
					} 
				}
			?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
  </div>
</section>
<?php $this->end() ?>
