<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
	<dd> <?php 
		$xml = simplexml_load_file('templates/planes/planeDescription.xml') or die("Error: Cannot create object");
		
	?>
	</dd>
	<h2>The plane for you is ....</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				$ans = $answer 
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				
				echo $ans;

				foreach($xml->children() as $planes) { 
					$name = $planes->name->__toString();
					
					if (strcmp($ans, $name) == 0) {
						echo "name     : " . $planes->name    . "<br>";
						echo "price    : " . $planes->price   . "<br>";
						echo "seats    : " . $planes->seats   . "<br>";
						echo "purpose  : " . $planes->purpose . "<br>";
						echo "niveau   : " . $planes->niveau  . "<br>";
						echo "flaps    : " . $planes->flaps   . "<br>";
						echo "year     : " . $planes->year    . "<br>";
						echo "wingspan: " . $planes->wingspan . "<br>";
						echo "class   : " . $planes->class    . "<br>";  
					}
				} 
			?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
<?php $this->end() ?>
