<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->html($domain->title) ?></title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="webfrontend">
		<nav class="site-nav">
			<a href="<?=$this->attr($_SERVER['REQUEST_URI'])?>">Restart</a>
		</nav>
		<header>
			<h1><?=$this->html($domain->title)?></h1>
			<p><?=$domain->description?></p>
		</header>
		<div>
			<form method="post">
				<input type="hidden" name="state" value="<?=_encode($state) ?>">
				<input type="hidden" name="log" value="<?=_encode($log) ?>">
				<?=$content?>
			</form>
		</div>

		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script>
		/* when clicking on an item, select the accompanying radio-button
		and submit the form. Unless the user clicks on a link. */
		$('.question > .options > li')
			.addClass('single-click')
			.click(function(e) {
				if (e.target.nodeName == 'A')
					return;

				var radio = $(this).find('input[type=radio]');
				radio.prop('checked', true);
				e.preventDefault();
				radio.get(0).form.submit();
			});
		
		$('.question button[type=submit]').hide();

		var panel = $('#debug-info');

		var grippy = $('<div>').addClass('grippy').appendTo(panel);

		var delta = 15;


		function removeResizeListener() {
			$(window)
				.off('mousemove', resizeDebugPanel)
				.off('mouseup', removeResizeListener);
		}

		grippy.mousedown(function(e) {
			e.preventDefault();
			jQuery(window)
				.on('mousemove', resizeDebugPanel)
				.on('mouseup', removeResizeListener);
		});

		function updateLogLevel() {
			var logLevel = $('#log-level-selector').val();
			localStorage.logLevel = logLevel;

			$('.state-info.log li').each(function() {
				var messageLogLevel = this.className.match(/log-level-(\d)/);
				$(this).toggle(!messageLogLevel || messageLogLevel[1] >= logLevel);
			});
		}

		$('#log-level-selector')
			.change(updateLogLevel)
			.val(localStorage.logLevel || <?=LOG_LEVEL_INFO?>);

		updateLogLevel();
		</script>
	</body>
</html>
